name: quran_player
description: Simple Quran audio player for the mobile app technical test.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  http: ^1.2.2
  just_audio: ^0.10.5
  shared_preferences: ^2.3.3
  marquee: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
